default_agent: backtest_agent
agents:
  backtest_agent:
    name: backtest_agent
    entrypoint: /Users/yfchiuaa/workspace/projects/sample-tech-for-trading/agentic_backtesting/agentcore-enablement/agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/yfchiuaa/workspace/projects/sample-tech-for-trading/agentic_backtesting/agentcore-enablement
    aws:
      execution_role: arn:aws:iam::600627331406:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-10b69e4c55
      execution_role_auto_create: false
      account: '600627331406'
      region: us-east-1
      ecr_repository: 600627331406.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-backtest_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: backtest_agent-NaVkRa7c5k
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:600627331406:runtime/backtest_agent-NaVkRa7c5k
      agent_session_id: a9f5648b-f6e2-43d1-87e6-71619ba3f6fc
    codebuild:
      project_name: bedrock-agentcore-backtest_agent-builder
      execution_role: arn:aws:iam::600627331406:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-10b69e4c55
      source_bucket: bedrock-agentcore-codebuild-sources-600627331406-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
