default_agent: quant_agent
agents:
  quant_agent:
    name: quant_agent
    entrypoint: /Users/awsjacky/Library/CloudStorage/WorkDocsDrive-Documents/projects/sample-tech-for-trading/agentic_backtesting/quant-agent-runtime/quant_agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/awsjacky/Library/CloudStorage/WorkDocsDrive-Documents/projects/sample-tech-for-trading/agentic_backtesting/quant-agent-runtime
    aws:
      execution_role: arn:aws:iam::600627331406:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-a6f76213c2
      execution_role_auto_create: false
      account: '600627331406'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-600627331406-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: quant_agent-D6li6lBv47
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:600627331406:runtime/quant_agent-D6li6lBv47
      agent_session_id: e4e96e20-98e7-402f-beaf-7cc4bff09be0
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: quant_agent_mem-5lxLrGHalh
      memory_arn: null
      memory_name: quant_agent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
